# Generated by Django 3.2.2 on 2021-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('wrtier', models.CharField(max_length=100)),
                ('pud_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
